[package]
name = "nasarud"
version = "0.0.1"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
libc = "0.2"
nasaru-android-bridge = { path = "../android-bridge" }
nasaru-android-shell-backend = { path = "../android-shell-backend" }
nasaru-local-transport = { path = "../local-transport" }
nasaru-riksu = { path = "../riksu" }
nasaru-runtime = { path = "../runtime" }
nasaru-signal-state = { path = "../signal-state" }
nasaru-signal-wire = { path = "../signal-wire" }

[lib]
name = "nasaru_daemon"
path = "src/lib.rs"

[[bin]]
name = "nasarud"
path = "src/main.rs"
